
export const tempOBJ = {
    "totalHits": 6,
    "currentPage": 1,
    "totalPages": 6,
    "pageList": [
        1,
        2,
        3,
        4,
        5,
        6
    ],
    "foodSearchCriteria": {
        "dataType": [
            "Foundation"
        ],
        "query": "1 lb Fresh spinach ",
        "generalSearchInput": "1 lb Fresh spinach ",
        "pageNumber": 1,
        "numberOfResultsPerPage": 50,
        "pageSize": 1,
        "requireAllWords": false,
        "foodTypes": [
            "Foundation"
        ]
    },
    "foods": [
        {
            "fdcId": 1999632,
            "description": "Spinach, baby",
            "commonNames": "",
            "additionalDescriptions": "",
            "dataType": "Foundation",
            "ndbNumber": 100260,
            "publishedDate": "2021-10-28",
            "foodCategory": "Vegetables and Vegetable Products",
            "mostRecentAcquisitionDate": "2021-01-25",
            "allHighlightFields": "",
            "score": 363.75116,
            "microbes": [],
            "foodNutrients": [
                {
                    "nutrientId": 1089,
                    "nutrientName": "Iron, Fe",
                    "nutrientNumber": "303",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 1.26,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5400,
                    "indentLevel": 1,
                    "foodNutrientId": 24470064,
                    "dataPoints": 8,
                    "min": 1.02,
                    "max": 1.6,
                    "median": 1.24
                },
                {
                    "nutrientId": 1090,
                    "nutrientName": "Magnesium, Mg",
                    "nutrientNumber": "304",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 92.9,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5500,
                    "indentLevel": 1,
                    "foodNutrientId": 24470065,
                    "dataPoints": 8,
                    "min": 81.8,
                    "max": 107,
                    "median": 90.3
                },
                {
                    "nutrientId": 1091,
                    "nutrientName": "Phosphorus, P",
                    "nutrientNumber": "305",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 39,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5600,
                    "indentLevel": 1,
                    "foodNutrientId": 24470066,
                    "dataPoints": 8,
                    "min": 31.1,
                    "max": 49.6,
                    "median": 39.9
                },
                {
                    "nutrientId": 1092,
                    "nutrientName": "Potassium, K",
                    "nutrientNumber": "306",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 582,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5700,
                    "indentLevel": 1,
                    "foodNutrientId": 24470067,
                    "dataPoints": 8,
                    "min": 433,
                    "max": 700,
                    "median": 566
                },
                {
                    "nutrientId": 1093,
                    "nutrientName": "Sodium, Na",
                    "nutrientNumber": "307",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 111,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5800,
                    "indentLevel": 1,
                    "foodNutrientId": 24470068,
                    "dataPoints": 8,
                    "min": 55.4,
                    "max": 224,
                    "median": 92.4
                },
                {
                    "nutrientId": 1095,
                    "nutrientName": "Zinc, Zn",
                    "nutrientNumber": "309",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.447,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5900,
                    "indentLevel": 1,
                    "foodNutrientId": 24470069,
                    "dataPoints": 8,
                    "min": 0.319,
                    "max": 0.597,
                    "median": 0.433
                },
                {
                    "nutrientId": 1161,
                    "nutrientName": "cis-Lutein/Zeaxanthin",
                    "nutrientNumber": "338.3",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7561,
                    "indentLevel": 2,
                    "foodNutrientId": 24470070,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1098,
                    "nutrientName": "Copper, Cu",
                    "nutrientNumber": "312",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.0818,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6000,
                    "indentLevel": 1,
                    "foodNutrientId": 24470071,
                    "dataPoints": 8,
                    "min": 0.064,
                    "max": 0.121,
                    "median": 0.0766
                },
                {
                    "nutrientId": 1162,
                    "nutrientName": "Vitamin C, total ascorbic acid",
                    "nutrientNumber": "401",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 26.5,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6300,
                    "indentLevel": 1,
                    "foodNutrientId": 24470072,
                    "dataPoints": 8,
                    "min": 9.87,
                    "max": 54.7,
                    "median": 26.4
                },
                {
                    "nutrientId": 1100,
                    "nutrientName": "Iodine, I",
                    "nutrientNumber": "314",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6150,
                    "indentLevel": 1,
                    "foodNutrientId": 24470073,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1165,
                    "nutrientName": "Thiamin",
                    "nutrientNumber": "404",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.0769,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6400,
                    "indentLevel": 1,
                    "foodNutrientId": 24470074,
                    "dataPoints": 8,
                    "min": 0.059,
                    "max": 0.105,
                    "median": 0.072
                },
                {
                    "nutrientId": 1101,
                    "nutrientName": "Manganese, Mn",
                    "nutrientNumber": "315",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.488,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6100,
                    "indentLevel": 1,
                    "foodNutrientId": 24470075,
                    "dataPoints": 8,
                    "min": 0.367,
                    "max": 0.733,
                    "median": 0.452
                },
                {
                    "nutrientId": 1166,
                    "nutrientName": "Riboflavin",
                    "nutrientNumber": "405",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.194,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6500,
                    "indentLevel": 1,
                    "foodNutrientId": 24470076,
                    "dataPoints": 8,
                    "min": 0.172,
                    "max": 0.223,
                    "median": 0.194
                },
                {
                    "nutrientId": 1103,
                    "nutrientName": "Selenium, Se",
                    "nutrientNumber": "317",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6200,
                    "indentLevel": 1,
                    "foodNutrientId": 24470077,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1167,
                    "nutrientName": "Niacin",
                    "nutrientNumber": "406",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.551,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6600,
                    "indentLevel": 1,
                    "foodNutrientId": 24470078,
                    "dataPoints": 8,
                    "min": 0.435,
                    "max": 0.81,
                    "median": 0.53
                },
                {
                    "nutrientId": 1107,
                    "nutrientName": "Carotene, beta",
                    "nutrientNumber": "321",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 3400,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7440,
                    "indentLevel": 2,
                    "foodNutrientId": 24470079,
                    "dataPoints": 8,
                    "min": 3030,
                    "max": 4000,
                    "median": 3330
                },
                {
                    "nutrientId": 1108,
                    "nutrientName": "Carotene, alpha",
                    "nutrientNumber": "322",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7450,
                    "indentLevel": 2,
                    "foodNutrientId": 24470080,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1175,
                    "nutrientName": "Vitamin B-6",
                    "nutrientNumber": "415",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.195,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6800,
                    "indentLevel": 1,
                    "foodNutrientId": 24470081,
                    "dataPoints": 8,
                    "min": 0.146,
                    "max": 0.252,
                    "median": 0.197
                },
                {
                    "nutrientId": 1176,
                    "nutrientName": "Biotin",
                    "nutrientNumber": "416",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 1.66,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6850,
                    "indentLevel": 1,
                    "foodNutrientId": 24470082,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 4.76,
                    "median": 0
                },
                {
                    "nutrientId": 1177,
                    "nutrientName": "Folate, total",
                    "nutrientNumber": "417",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 116,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 6900,
                    "indentLevel": 1,
                    "foodNutrientId": 24470083,
                    "dataPoints": 8,
                    "min": 90.4,
                    "max": 155,
                    "median": 120
                },
                {
                    "nutrientId": 1051,
                    "nutrientName": "Water",
                    "nutrientNumber": "255",
                    "unitName": "G",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 92.5,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 100,
                    "indentLevel": 1,
                    "foodNutrientId": 24470084,
                    "dataPoints": 8,
                    "min": 90.8,
                    "max": 93.5,
                    "median": 92.8
                },
                {
                    "nutrientId": 1118,
                    "nutrientName": "Carotene, gamma",
                    "nutrientNumber": "332",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7455,
                    "indentLevel": 2,
                    "foodNutrientId": 24470085,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1119,
                    "nutrientName": "Zeaxanthin",
                    "nutrientNumber": "338.2",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 191,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7564,
                    "indentLevel": 2,
                    "foodNutrientId": 24470086,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 511,
                    "median": 146
                },
                {
                    "nutrientId": 1120,
                    "nutrientName": "Cryptoxanthin, beta",
                    "nutrientNumber": "334",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7460,
                    "indentLevel": 2,
                    "foodNutrientId": 24470087,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1121,
                    "nutrientName": "Lutein",
                    "nutrientNumber": "338.1",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 5830,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7562,
                    "indentLevel": 2,
                    "foodNutrientId": 24470088,
                    "dataPoints": 8,
                    "min": 5320,
                    "max": 7110,
                    "median": 5560
                },
                {
                    "nutrientId": 1122,
                    "nutrientName": "Lycopene",
                    "nutrientNumber": "337",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7530,
                    "indentLevel": 1,
                    "foodNutrientId": 24470089,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1002,
                    "nutrientName": "Nitrogen",
                    "nutrientNumber": "202",
                    "unitName": "G",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.456,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 500,
                    "indentLevel": 1,
                    "foodNutrientId": 24470090,
                    "dataPoints": 8,
                    "min": 0.4,
                    "max": 0.54,
                    "median": 0.43
                },
                {
                    "nutrientId": 1004,
                    "nutrientName": "Total lipid (fat)",
                    "nutrientNumber": "204",
                    "unitName": "G",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0.619,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 800,
                    "indentLevel": 1,
                    "foodNutrientId": 24470091,
                    "dataPoints": 8,
                    "min": 0.54,
                    "max": 0.73,
                    "median": 0.605
                },
                {
                    "nutrientId": 1007,
                    "nutrientName": "Ash",
                    "nutrientNumber": "207",
                    "unitName": "G",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 1.6,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 1000,
                    "indentLevel": 1,
                    "foodNutrientId": 24470092,
                    "dataPoints": 8,
                    "min": 1.37,
                    "max": 1.82,
                    "median": 1.6
                },
                {
                    "nutrientId": 2032,
                    "nutrientName": "Cryptoxanthin, alpha",
                    "nutrientNumber": "335",
                    "unitName": "UG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 0,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7461,
                    "indentLevel": 2,
                    "foodNutrientId": 24470093,
                    "dataPoints": 8,
                    "min": 0,
                    "max": 0,
                    "median": 0
                },
                {
                    "nutrientId": 1079,
                    "nutrientName": "Fiber, total dietary",
                    "nutrientNumber": "291",
                    "unitName": "G",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 1.56,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 1200,
                    "indentLevel": 3,
                    "foodNutrientId": 24470094,
                    "dataPoints": 8,
                    "min": 1.2,
                    "max": 2.13,
                    "median": 1.5
                },
                {
                    "nutrientId": 1087,
                    "nutrientName": "Calcium, Ca",
                    "nutrientNumber": "301",
                    "unitName": "MG",
                    "derivationCode": "A",
                    "derivationDescription": "Analytical",
                    "derivationId": 1,
                    "value": 68.4,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 5300,
                    "indentLevel": 1,
                    "foodNutrientId": 24470095,
                    "dataPoints": 8,
                    "min": 48.2,
                    "max": 92.1,
                    "median": 70.4
                },
                {
                    "nutrientId": 1003,
                    "nutrientName": "Protein",
                    "nutrientNumber": "203",
                    "unitName": "G",
                    "derivationCode": "NC",
                    "derivationDescription": "Calculated",
                    "derivationId": 49,
                    "value": 2.85,
                    "foodNutrientSourceId": 2,
                    "foodNutrientSourceCode": "4",
                    "foodNutrientSourceDescription": "Calculated or imputed",
                    "rank": 600,
                    "indentLevel": 1,
                    "foodNutrientId": 24474188,
                    "min": 2.5,
                    "max": 3.38,
                    "median": 2.69
                },
                {
                    "nutrientId": 1005,
                    "nutrientName": "Carbohydrate, by difference",
                    "nutrientNumber": "205",
                    "unitName": "G",
                    "derivationCode": "NC",
                    "derivationDescription": "Calculated",
                    "derivationId": 49,
                    "value": 2.41,
                    "foodNutrientSourceId": 2,
                    "foodNutrientSourceCode": "4",
                    "foodNutrientSourceDescription": "Calculated or imputed",
                    "rank": 1110,
                    "indentLevel": 2,
                    "foodNutrientId": 24474189
                },
                {
                    "nutrientId": 1106,
                    "nutrientName": "Vitamin A, RAE",
                    "nutrientNumber": "320",
                    "unitName": "UG",
                    "derivationCode": "NC",
                    "derivationDescription": "Calculated",
                    "derivationId": 49,
                    "value": 283,
                    "foodNutrientSourceId": 2,
                    "foodNutrientSourceCode": "4",
                    "foodNutrientSourceDescription": "Calculated or imputed",
                    "rank": 7420,
                    "indentLevel": 1,
                    "foodNutrientId": 24474190
                },
                {
                    "nutrientId": 2047,
                    "nutrientName": "Energy (Atwater General Factors)",
                    "nutrientNumber": "957",
                    "unitName": "KCAL",
                    "derivationCode": "NC",
                    "derivationDescription": "Calculated",
                    "derivationId": 49,
                    "value": 26.6,
                    "foodNutrientSourceId": 2,
                    "foodNutrientSourceCode": "4",
                    "foodNutrientSourceDescription": "Calculated or imputed",
                    "rank": 280,
                    "indentLevel": 1,
                    "foodNutrientId": 24474191
                },
                {
                    "nutrientId": 2048,
                    "nutrientName": "Energy (Atwater Specific Factors)",
                    "nutrientNumber": "958",
                    "unitName": "KCAL",
                    "derivationCode": "NC",
                    "derivationDescription": "Calculated",
                    "derivationId": 49,
                    "value": 20.7,
                    "foodNutrientSourceId": 2,
                    "foodNutrientSourceCode": "4",
                    "foodNutrientSourceDescription": "Calculated or imputed",
                    "rank": 290,
                    "indentLevel": 1,
                    "foodNutrientId": 24474192
                },
                {
                    "nutrientId": 1123,
                    "nutrientName": "Lutein + zeaxanthin",
                    "nutrientNumber": "338",
                    "unitName": "UG",
                    "derivationCode": "AS",
                    "derivationDescription": "Summed",
                    "derivationId": 4,
                    "value": 6020,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 7560,
                    "indentLevel": 1,
                    "foodNutrientId": 24474194
                },
                {
                    "nutrientId": 1050,
                    "nutrientName": "Carbohydrate, by summation",
                    "nutrientNumber": "205.2",
                    "unitName": "G",
                    "derivationCode": "AS",
                    "derivationDescription": "Summed",
                    "derivationId": 4,
                    "value": 1.56,
                    "foodNutrientSourceId": 1,
                    "foodNutrientSourceCode": "1",
                    "foodNutrientSourceDescription": "Analytical or derived from analytical",
                    "rank": 1120,
                    "indentLevel": 2,
                    "foodNutrientId": 26845143
                }
            ],
            "finalFoodInputFoods": [],
            "foodMeasures": [],
            "foodAttributes": [],
            "foodAttributeTypes": [],
            "foodVersionIds": []
        }
    ],
    "aggregations": {
        "dataType": {
            "Branded": 293166,
            "SR Legacy": 772,
            "Survey (FNDDS)": 308,
            "Experimental": 11,
            "Foundation": 6
        },
        "nutrients": {}
    }
}